springdoc:
  swagger-ui:
    oauth:
      client-id: swagger_test
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        prompt: login

spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
