spring:
  application:
    name: book-msvc

server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:book_msvc}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/library-management-api}

springdoc:
  swagger-ui:
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:swagger_test}
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        prompt: login
