server:
  port: ${SERVER_PORT}

spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      bindings:
        loan-events-out-0:
          destination: loan-events
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_URI}

copy-msvc:
  url: ${COPY_MSVC_URL}

user-msvc:
  url: ${USER_MSVC_URL}

# Observability
management:
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
